
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060102
// Wed May 13 22:56:16 BRT 2009
//----------------------------------------------------

package br.fbv.compiladores.projeto;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int MAIS = 2;
  public static final int MENOS = 3;
  public static final int DIVIDIDO = 5;
  public static final int EOF = 0;
  public static final int VEZES = 4;
  public static final int NUMERO = 9;
  public static final int error = 1;
  public static final int ABRE_PAR = 7;
  public static final int PT_VIRG = 6;
  public static final int FECHA_PAR = 8;
}

