
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 07 00:02:52 GMT-03:00 2011
//----------------------------------------------------

package br.fbv.examples.cup.interpreter;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int MAIS = 2;
  public static final int MENOS = 3;
  public static final int DIVIDIDO = 5;
  public static final int EOF = 0;
  public static final int VEZES = 4;
  public static final int NUMERO = 9;
  public static final int error = 1;
  public static final int ABRE_PAR = 7;
  public static final int PT_VIRG = 6;
  public static final int FECHA_PAR = 8;

  /* non terminals */
  static final int program = 1;
  static final int comand = 2;
  static final int expr = 0;
}

