
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 11 18:42:11 BRT 2009
//----------------------------------------------------

package br.fbv.compiladores.projeto;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAIS = 2;
  public static final int MENOS = 3;
  public static final int DIVIDIDO = 5;
  public static final int EOF = 0;
  public static final int VEZES = 4;
  public static final int NUMERO = 9;
  public static final int error = 1;
  public static final int ABRE_PAR = 7;
  public static final int PT_VIRG = 6;
  public static final int FECHA_PAR = 8;
}

